### ISSUE TITLE
Invalid Property Value when parsing

### ISSUE THREAD

**Issue by kurnevsky** [julianandrews/sgf-parse#8]
This game can't be parsed: [zagram352562.txt](https://github.com/julianandrews/sgf-parse/files/5842577/zagram352562.txt)

It's taken from http://eidokropki.reaktywni.pl/index.phtml#url:zagram352562

I guess it's because moves can contain surroundings besides coordinates which is written like `W[rp.pmonpoqprpsornqmpm]`. According to the [spec](https://www.red-bean.com/sgf/sgf4.html#move/pos) move is game specific and therefore shouldn't be parsed for unknown games.

Also [spec](https://www.red-bean.com/sgf/sgf4.html#2.2.3) says that invalid properties should be corrected or ignored.

**Comment by julianandrews** [comment]
Sorry for the slow reply on this - my notification settings are a little off in github. I've split this into two issues that are more on point. Please comment on either if you have thoughts about the proposed fixes!

**Comment by julianandrews** [comment]
I'm going to close this issue since the fix for #10 should also fix the immediate problem here. Leaving #9 open for if/when I have time to figure out the best approach.
